apiVersion: apps/v1
kind: Deployment
metadata:
  name: beverage
  labels:
    app: beverage
spec:
  replicas: 1
  selector:
    matchLabels:
      app: beverage
  template:
    metadata:
      labels:
        app: beverage
    spec:
      containers:
        - name: beverage
          image: "user18.azurecr.io/beverage:latest"
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: "200m"
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5
